### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by Mike-DE-RE** [RWAP/PrinterToPDF#13]
Latest version of code (10.05.2017, 22:15) has following problems:

gcc PrinterConvert.c -o PrinterConvert -lSDL -lpng -lrt -ggdb
PrinterConvert.c: In function ‘initialize’:
PrinterConvert.c:110: error: ‘marginleftp’ undeclared (first use in this function)
PrinterConvert.c:110: error: (Each undeclared identifier is reported only once
PrinterConvert.c:110: error: for each function it appears in.)
PrinterConvert.c:110: error: ‘marginrightp’ undeclared (first use in this function)
PrinterConvert.c:111: error: ‘margintopp’ undeclared (first use in this function)
PrinterConvert.c:111: error: ‘marginbottomp’ undeclared (first use in this function)

When you add
int initialize()
{

int marginleftp = 0;
int marginrightp = 0;
int margintopp = 0;
int marginbottomp = 0;

it compiles without errors.

**Comment by RWAP** [comment]
This has been fixed
