### ISSUE TITLE
readme shell commands need to markdown escape the backticks

### ISSUE THREAD

**Issue by jedimatt42** [RWAP/PrinterToPDF#21]
https://daringfireball.net/projects/markdown/syntax#backslash

Not being familiar with sdl, the sdl-config parameters made no sense in the README.md, because the backticks are translated by markdown.

If you use triple-back-tick instead of html code tag, you'll get what you want:

```
gcc PrinterConvert.c `sdl-config --cflags --libs` -o printerToPDF -lrt -lhpdf -lpng
```

**Comment by RWAP** [comment]
Many thanks - amended the readme file accordingly
