### ISSUE TITLE
Implement a "clean" command line interface next= use switches which have default values if omitted. That will include a switch to set the paper size so you won't have to set it manually inside the initialize() function any more.

### ISSUE THREAD

**Issue by RWAP** [RWAP/PrinterToPDF#28]
I would like to implement a "clean" command line interface next. My goal is to get away from a strict order and replace that by switches which have default values if omitted. That will include a switch to set the paper size so you won't have to set it manually inside the initialize() function any more.

_Originally posted by @rosenrost in https://github.com/RWAP/PrinterToPDF/pull/27#issuecomment-675590607_

**Comment by rosenrost** [comment]
Can be closed.
