### ISSUE TITLE
Rendering corruption 

### ISSUE THREAD

**Issue by tomverbeure** [RWAP/PrinterToPDF#37]
I have been trying PrinterToPDF with a TDS 420A oscilloscope and an Advantest R3273 spectrum analyzer. On both devices, I'm seeing corruption in the PDF file. I've captured the data with my parallel port capture tool (see [here](https://twitter.com/tom_verbeure/status/1613338752507867136)), so it's possible that it has a bug, but both for both devices, when I capture a screenshot of the same image (with minor changes, such as waveform or time), the corruption is always in the same place, so the error is deterministic.

In the case of the TDS 420A, I used "Epson 9 & 24 pin dot matrix printer" as output format. With the Advantest, I see corruption with "ESC/P Gray" and "ESC/P Mono S" modes. However, if I select "ESC/P Mono L", I have so far never seen a corruption.

I don't know enough about the ESC/P format to understand the differences between Gray/Mono S/Mono L.

In attachment are a bunch of traces from the Advantest: [sa_esc_p_traces.tar.gz](https://github.com/RWAP/PrinterToPDF/files/10421976/sa_esc_p_traces.tar.gz)

I'm using the following command line:

`/opt/printerToPDF/bin/printerToPDF -o output -f /opt/printerToPDF/lib/PrinterToPDF/font2/Epson-Standard.C16 sa_esc_p_gray_a.esc_p`

And here are a couple of examples of corruption:

![sa_esc_p_gray_a](https://user-images.githubusercontent.com/36720790/212583126-2f007256-04a9-473b-9c17-0638156a073e.png)

![sa_a](https://user-images.githubusercontent.com/36720790/212583142-97160fbb-7d7d-4690-889b-2190de2bbb33.png)

![tds_420a_a](https://user-images.githubusercontent.com/36720790/212583146-ac21ee97-41f2-43f8-baa2-5bfffc2ff8d7.png)

**Comment by tomverbeure** [comment]
To be clear: it's totally possible that this is an issue with the scope and the spectrum analyzer. Feel free to ignore if this software have been reliable for many other sources.

**Comment by RWAP** [comment]
That is an interesting issue the last one in particular - as it happens at the start of every line (and oddly the column above the o in "Layout"

Unfortunately, the only way of checking is by working through the raw captured data to see if it indicates an ESC/P command which is not currently emulated, or being abused by the spectrum analyser (eg using an undocumented parameter).

**Comment by RWAP** [comment]
Also wondering what those lines are in top left of the final image under Tel < Run ?

**Comment by tomverbeure** [comment]
Here is a trace with a bunch of TDS 420A Epson captures in a row: [tds_epson_9_24_c.esc_p.gz](https://github.com/RWAP/PrinterToPDF/files/10428794/tds_epson_9_24_c.esc_p.gz)

The corruption is mostly at the same location, but there's variability as well.

Page 4 is probably the one you'd like to look at first, because it has corruption right at the start:

![tds_corruption](https://user-images.githubusercontent.com/36720790/212752817-1e1aa2fa-3aae-4ba5-a6e1-b6b34ac87544.png)

This is the command line:

`/opt/printerToPDF/bin/printerToPDF -o output -f /opt/printerToPDF/lib/PrinterToPDF/font2/Epson-Standard.C16 tds_epson_9_24_c.esc_p`

Keep in mind that I can't 100% rule out an issue with the captured trace. I will add a checksum calculation at the capturing side to make sure that the data transfer over the serial USB link is error free.

**Comment by RWAP** [comment]
The problem is working out where in the code page 4 starts - can you not print just that one page and see if you still get the corruption?  If not, then it is probably a timing issue - particularly as everything is being sent as graphics - it only takes a small error to cause corruption.

Of course, as graphics also (strips of 9 pin high graphics), there is next to no chance of identiying where one page ends and another starts!

**Comment by tomverbeure** [comment]
I found the issue: when writing to the USB UART, the Raspberry Pico will by default convert 0x0a into 0x0a 0x0d. This is why the corruption was deterministic...

Sorry for this!

Closing.

**Comment by RWAP** [comment]
Great - I did wonder if it might be something along the line endings, but the fact corruption seemed to happen towards the right hand side also was puzzling me.
