### ISSUE TITLE
Segmentation fault when parameter missing

### ISSUE THREAD

**Issue by Mike-DE-RE** [RWAP/PrinterToPDF#4]
Instead of

./PrinterConvert 4 3 SIEMENS.C16 1 sdlon ./

I tried

./PrinterConvert 4 3 SIEMENS.C16 1 ./

to suppress graphic output. Result is a segmentation fault instead of an error message.

**Comment by RWAP** [comment]
You need to use sdloff for now - ideally the program needs a better user interface - but that is not something I plan to release as this is just an extraction of the routines used in our Retro-Printer device for others to build into a fully fledged conversion program

**Comment by Mike-DE-RE** [comment]
Ok, fine. sdloff does what I wanted. Can be closed.
