### ISSUE TITLE
Huge files (bmp, pdf), long conversion time

### ISSUE THREAD

**Issue by Mike-DE-RE** [RWAP/PrinterToPDF#6]
Any specific reason why you decided for bmp as base for PrinterToPDF?

The files I get are huge

bmp is 144MB
pdf is 130 MB.

The conversion time from bmp to pdf is dramatic. Are you aware of the wonderful little helpers under linux?

/// Doing this

time ./PrinterConvert 4 3 SIEMENS.C16 1 sdlon ./

delays around ack: t1=0    t2=0    t3=0    t4=0    t5=0

I am at page 1
write   = bmp/page1.bmp
command = convert  bmp/page1.bmp  ./pdf/page1.pdf

real    9m30.811s
user    0m58.736s
sys     0m10.897s

takes 9 Minutes 30 Seconds.

/// Doing this instead

time bmp2tiff -c none page1.bmp page1.tif

real    0m6.487s
user    0m0.180s
sys     0m0.984s

time tiff2pdf page1.tif -o page.pdf -z

real    1m33.701s
user    0m7.484s
sys     0m2.540s

takes only 1 Minute 40 seconds.

Uncompressed tif is 144 MB, compressed pdf is 891 KB.

Have not had the time to compare 100% but pdfs look quite identical.

Your pdf:
[PrinterToPDF.zip](https://github.com/RWAP/PrinterToPDF/files/986340/PrinterToPDF.zip)

Converted pdf:
[page.pdf](https://github.com/RWAP/PrinterToPDF/files/986343/page.pdf)

**Comment by RWAP** [comment]
Hmm - unfortunately, bmp2tiff is not available on debian due to a security issue - https://www.debian.org/security/2017/dsa-3762 (Raspberry Pi uses debian).

There must be something quicker than the ImageMagick Convert function ...

**Comment by Mike-DE-RE** [comment]
I know this is little unusual but should show conversion time

**/// 1st step**

time bmptoppm page1.bmp >page1.ppm
bmptoppm: Windows BMP, 5954x8417x24
bmptoppm: WRITING PPM IMAGE

real    1m37.099s
user    0m7.988s
sys     0m3.320s

**/// 2nd step**

time ppm2tiff page1.ppm page1.tif

real    0m5.941s
user    0m1.976s
sys     0m2.056s

**/// Result**

144M  page1.bmp
144M  page1.ppm
130M  page1.tif

**/// compressed tiff**

time ppm2tiff -c lzw page1.ppm page1.tif

real    0m4.076s
user    0m2.028s
sys     0m1.400s

**/// Result**

4,0M  page1.tif

Why do you start from bmp?

**Comment by Mike-DE-RE** [comment]
I've tried with a "print to file" from Microsoft Word for DOS.

[EPSON.zip](https://github.com/RWAP/PrinterToPDF/files/987036/EPSON.zip)

time ./PrinterConvert 4 3 SIEMENS.C16 1 sdlon ./

delays around ack: t1=0    t2=0    t3=0    t4=0    t5=0
write   = bmp/page2.bmp
command = convert  bmp/page2.bmp  ./pdf/page2.pdf


I am at page 3
write   = bmp/page3.bmp
command = convert  bmp/page3.bmp  ./pdf/page3.pdf

real    28m55.837s
user    1m42.998s
sys     0m21.809s

Print started with page 2, why? Because there was a page 1 from former conversion?

Print showes two pages (second page is blank), I am quite sure it has one page only. I did this test file for Epson because their WorkForce printers claim to offer ESC/P2. As a matter of fact, the file did not print on any of their printers.

**Comment by RWAP** [comment]
A good question - I am now using the libgd library to create a jpg image instead of bmp and that is then converted to pdf.  We could possibly use a jpg2tiff (if there is one available for Debian) to convert the final image.

See updated code and also the new instructions in readme.md

I will have a look at the Epson file.

The files start with page2.jpg and page2.pdf because the system does not overwrite the old page dumps in the folders.

**Comment by RWAP** [comment]
Now using libpng rather than libgd - however, convert is still needed.

**Comment by Mike-DE-RE** [comment]
Cannot compile the new code:

cc PrinterConvert.c -o PrinterConvert -lSDL -lrt -ggdb
/tmp/cc5Q0aiv.o: In function `write_png':
/home/user/PrinterToPDF/PrinterConvert.c:286: undefined reference to `png_create_write_struct'
/home/user/PrinterToPDF/PrinterConvert.c:294: undefined reference to `png_create_info_struct'
/home/user/PrinterToPDF/PrinterConvert.c:301: undefined reference to `png_set_compression_level'
/home/user/PrinterToPDF/PrinterConvert.c:310: undefined reference to `png_init_io'
/home/user/PrinterToPDF/PrinterConvert.c:313: undefined reference to `png_set_IHDR'
/home/user/PrinterToPDF/PrinterConvert.c:323: undefined reference to `png_set_text'
/home/user/PrinterToPDF/PrinterConvert.c:326: undefined reference to `png_write_info'
/home/user/PrinterToPDF/PrinterConvert.c:355: undefined reference to `png_write_rows'
/home/user/PrinterToPDF/PrinterConvert.c:361: undefined reference to `png_write_rows'
/home/user/PrinterToPDF/PrinterConvert.c:365: undefined reference to `png_write_end'
/home/user/PrinterToPDF/PrinterConvert.c:369: undefined reference to `png_free_data'
/home/user/PrinterToPDF/PrinterConvert.c:370: undefined reference to `png_destroy_write_struct'
collect2: ld returned 1 exit status

**Comment by RWAP** [comment]
Good morning - did you change the gcc command as per the readme.md on here?  you need to ensure you have -lpng at the end

**Comment by Mike-DE-RE** [comment]
Sorry! Did not see that.

**Comment by Mike-DE-RE** [comment]
File size decreased with the new png routines. This issue can be closed.
